name: Build and Attach Release APK

on:
  push:
    tags:
      - '*' # Trigger on any tag
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required to upload artifacts and create releases

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: '34.0.0'
          ndk: '23.1.7779620'

      # Step 4: Grant execute permissions to Gradle wrapper
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Step 5: Build the release APK
      - name: Build release APK
        run: ./gradlew assembleRelease

      # Step 6: Upload the APK as an artifact
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

      # Step 7: Conditionally upload the APK to a release
      - name: Upload APK to GitHub Release
        if: startsWith(github.ref, 'refs/tags/') # Only run if triggered by a tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/outputs/apk/release/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}